# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-07 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='opinia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('ocena', models.CharField(blank=True, choices=[('S', 'Super'), ('D', 'Dobrze'), ('Z', '\u0179le'), ('T', 'Tragedia')], max_length=1)),
                ('tresc', models.TextField(max_length=500)),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['data'],
            },
        ),
    ]
