# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularz_kontaktowy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kontakt',
            options={'ordering': ['imie_i_nazwisko']},
        ),
        migrations.RenameField(
            model_name='kontakt',
            old_name='i_i_n',
            new_name='imie_i_nazwisko',
        ),
        migrations.RenameField(
            model_name='kontakt',
            old_name='rodzaj_nier',
            new_name='rodzaj_nieruchomosci',
        ),
    ]
