# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_product', models.CharField(choices=[('B', 'Bi\u017cuteria'), ('T', 'Telefon'), ('TA', 'Tablet'), ('L', 'Laptop'), ('I', 'Inne')], default='B', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='product_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_kat', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('producent', models.CharField(blank=True, choices=[('A', 'Apple'), ('H', 'Huawei'), ('S', 'Samsung'), ('LG', 'LG'), ('M', 'Microsoft'), ('LV', 'Lenovo'), ('AS', 'Asus'), ('SN', 'Sony'), ('IN', 'Inny')], max_length=2)),
                ('system', models.CharField(blank=True, choices=[('I', 'iOS'), ('AD', 'Android')], max_length=2)),
                ('size', models.PositiveIntegerField(blank=True)),
                ('memory', models.PositiveIntegerField(blank=True)),
                ('type', models.CharField(blank=True, choices=[('K', 'Kolczyki'), ('P', 'Pier\u015bcionki'), ('N', 'Naszyjniki'), ('B', 'Bransoletki'), ('W', 'Wisiorki'), ('L', '\u0141a\u0144cuszki'), ('BR', 'Broszki')], max_length=2)),
                ('material', models.CharField(blank=True, choices=[('Z', 'Z\u0142oto'), ('SR', 'Srebro')], max_length=2)),
                ('photo', models.ImageField(blank=True, upload_to='photos/')),
                ('desription', models.TextField()),
                ('prize', models.DecimalField(decimal_places=2, max_digits=8)),
                ('count', models.PositiveIntegerField()),
                ('type_of_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produkty.product')),
            ],
            options={
                'ordering': ['nr_kat'],
            },
        ),
    ]
