# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(max_length=50),
        ),
    ]
