# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0004_auto_20161229_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_detail',
            name='type_of_product',
            field=models.CharField(choices=[('BI', 'Bi\u017cuteria'), ('TE', 'Telefony'), ('TA', 'Tablety'), ('LA', 'Laptopy'), ('IE', 'Inne')], default='IE', max_length=2),
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
