# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 21:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0005_auto_20161231_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_detail',
            name='pub_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
